# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: cef0300fd0fc4d2a87a85fa2093c6b283ea36f4b # v5.0.0
    hooks:
      - id: check-added-large-files
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
      - id: check-shebang-scripts-are-executable
  - repo: https://github.com/tekwizely/pre-commit-golang
    rev: bf2137dcd61fa219107613e4a4103cf24540cd93 # v1.0.0-rc.2
    hooks:
      - id: go-mod-tidy
      - id: go-test-mod
      - id: go-fmt
      - id: golangci-lint-mod
