version: "3.9"

services:
  minio:
    image: minio/minio
    ports:
      - "127.0.0.1:9000:9000"
      - "127.0.0.1:9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: 5ee4392a-cb32-4f9d-8c19-d91e19e30834
    volumes:
      - minio_data:/data
      - minio_config:/root/.minio
    command: server --console-address ":9001" /data

  minio-init:
    image: minio/mc
    entrypoint: ["sh", "-c"]
    command: >
      "mc config host add myminio http://minio:9000 admin 5ee4392a-cb32-4f9d-8c19-d91e19e30834 &&
       mc rb --force myminio/test-bucket || true &&
       mc mb myminio/test-bucket"
    depends_on:
      - minio

volumes:
  minio_data:
  minio_config:
